//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PANT
    {
        public int ID { get; set; }
        public string LOT_ { get; set; }
        public string STYLE_ { get; set; }
        public string ART { get; set; }
        public string COLOR { get; set; }
        public string COLORName { get; set; }
        public string yaowei { get; set; }
        public string C30W_29L { get; set; }
        public string C30W_30L { get; set; }
        public string C30W_32L { get; set; }
        public string C31W_30L { get; set; }
        public string C31W_32L { get; set; }
        public string C32W_28L { get; set; }
        public string C32W_30L { get; set; }
        public string C32W_32L { get; set; }
        public string C33W_29L { get; set; }
        public string C33W_30L { get; set; }
        public string C33W_32L { get; set; }
        public string C33W_34L { get; set; }
        public string C34W_29L { get; set; }
        public string C34W_30L { get; set; }
        public string C34W_31L { get; set; }
        public string C34W_32L { get; set; }
        public string C34W_34L { get; set; }
        public string C36W_29L { get; set; }
        public string C36W_30L { get; set; }
        public string C36W_32L { get; set; }
        public string C36W_34L { get; set; }
        public string C38W_29L { get; set; }
        public string C38W_30L { get; set; }
        public string C38W_32L { get; set; }
        public string C38W_34L { get; set; }
        public string C40W_28L { get; set; }
        public string C40W_30L { get; set; }
        public string C40W_32L { get; set; }
        public string C40W_34L { get; set; }
        public string C42W_30L { get; set; }
        public string C42W_32L { get; set; }
        public string C42W_34L { get; set; }
        public string C44W_29L { get; set; }
        public string C44W_30L { get; set; }
        public string C44W_32L { get; set; }
        public string Sub_Total { get; set; }
    }
}
