//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaiDan_SLIM
    {
        public int id { get; set; }
        public string DESC { get; set; }
        public string FABRIC { get; set; }
        public string STYLE { get; set; }
        public string shuoming { get; set; }
        public string Jacket { get; set; }
        public string Pant { get; set; }
        public string LABEL { get; set; }
        public string JiaGongchang { get; set; }
        public string CaiDanHao { get; set; }
        public string ZhiDanRiqi { get; set; }
        public string JiaoHuoRiqi { get; set; }
        public string RN_NO { get; set; }
        public string MianLiao { get; set; }
        public string LOT { get; set; }
        public string ChimaSTYLE { get; set; }
        public string ART { get; set; }
        public string COLOR { get; set; }
        public string COLORID { get; set; }
        public string JACKET_PANT { get; set; }
        public string C34R { get; set; }
        public string C36R { get; set; }
        public string C38R { get; set; }
        public string C40R { get; set; }
        public string C42R { get; set; }
        public string C44R { get; set; }
        public string C46R { get; set; }
        public string C48R { get; set; }
        public string C36L { get; set; }
        public string C38L { get; set; }
        public string C40L { get; set; }
        public string C42L { get; set; }
        public string C44L { get; set; }
        public string C46L { get; set; }
        public string C48L { get; set; }
        public string C34S { get; set; }
        public string C36S { get; set; }
        public string C38S { get; set; }
        public string C40S { get; set; }
        public string C42S { get; set; }
        public string C44S { get; set; }
        public string C46S { get; set; }
        public string Sub_Total { get; set; }
    }
}
