//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiMa_Dapeibiao
    {
        public int id { get; set; }
        public string LOT__面料 { get; set; }
        public string STYLE_款式 { get; set; }
        public string ART_货号 { get; set; }
        public string COLOR_颜色 { get; set; }
        public string COLOR__颜色编号 { get; set; }
        public string JACKET_上衣_PANT_裤子 { get; set; }
        public string C34R_28 { get; set; }
        public string C36R_30 { get; set; }
        public string C38R_32 { get; set; }
        public string C40R___34 { get; set; }
        public string C42R_36 { get; set; }
        public string C44R_38 { get; set; }
        public string C46R_40 { get; set; }
        public string C48R_42 { get; set; }
        public string C50R_44 { get; set; }
        public string C52R_46 { get; set; }
        public string C54R_48 { get; set; }
        public string C56R_50 { get; set; }
        public string C58R_52 { get; set; }
        public string C60R_54 { get; set; }
        public string C62R_56 { get; set; }
        public string C36L_30 { get; set; }
        public string C38L_32 { get; set; }
        public string C40L_34 { get; set; }
        public string C42L_36 { get; set; }
        public string C44L_38 { get; set; }
        public string C46L_40 { get; set; }
        public string C48L_42 { get; set; }
        public string C50L_44 { get; set; }
        public string C52L_46 { get; set; }
        public string C54L_48 { get; set; }
        public string C56L_50 { get; set; }
        public string C58L_52 { get; set; }
        public string C60L_54 { get; set; }
        public string C62L_56 { get; set; }
        public string C34S_28 { get; set; }
        public string C36S_30 { get; set; }
        public string C38S_32 { get; set; }
        public string C40S_34 { get; set; }
        public string C42S_36 { get; set; }
        public string C44S_38 { get; set; }
        public string C46S_40 { get; set; }
        public string DingdanHeji { get; set; }
    }
}
