//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_PANT
    {
        public int ID { get; set; }
        public string LOT_ { get; set; }
        public string STYLE_ { get; set; }
        public string ART { get; set; }
        public string COLOR { get; set; }
        public string COLORName { get; set; }
        public string yaowei { get; set; }
        public string C30W_R_30L { get; set; }
        public string C30W_L_32L { get; set; }
        public string C32W_R_30L { get; set; }
        public string C32W_L_32L { get; set; }
        public string C34W_S_38L { get; set; }
        public string C34W_S_39L { get; set; }
        public string C34W_R_30L { get; set; }
        public string C34W_L_32L { get; set; }
        public string C34W_L_34L { get; set; }
        public string C36W_S_28L { get; set; }
        public string C36W_S_29L { get; set; }
        public string C36W_R_30L { get; set; }
        public string C36W_R_31L { get; set; }
        public string C38W_S_28L { get; set; }
        public string C38W_R_30L { get; set; }
        public string C38W_R_31L { get; set; }
        public string C38W_L_32L { get; set; }
        public string C38W_L_34L { get; set; }
        public string C40W_S_28L { get; set; }
        public string C40W_S_29L { get; set; }
        public string C40W_R_30L { get; set; }
        public string C40W_R_31L { get; set; }
        public string C40W_L_32L { get; set; }
        public string C40W_L_34L { get; set; }
        public string C42W_R_30L { get; set; }
        public string C42W_L_32L { get; set; }
        public string C42W_L_34L { get; set; }
        public string C44W_R_30L { get; set; }
        public string C44W_L_32L { get; set; }
        public string C44W_L_34L { get; set; }
        public string C46W_R_30L { get; set; }
        public string C46W_L_32L { get; set; }
        public string C48W_R_30L { get; set; }
        public string C48W_L_32L { get; set; }
        public string C50W_L_32L { get; set; }
        public string Sub_Total { get; set; }
    }
}
