//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanHao
    {
        public int Id { get; set; }
        public string CaiDanNo { get; set; }
        public string Style { get; set; }
        public string FABRIC_CONTENT { get; set; }
        public string DATE { get; set; }
        public string JiaGongChang { get; set; }
        public string XuHao { get; set; }
        public string Name { get; set; }
        public string HuoHao { get; set; }
        public string GuiGe { get; set; }
        public string Yanse { get; set; }
        public string Danjia { get; set; }
        public string DanHao1 { get; set; }
        public string Jine { get; set; }
        public string BeiZhu { get; set; }
        public string ChangShang { get; set; }
        public string Heji { get; set; }
        public string Type { get; set; }
    }
}
