//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class GongHuoFang
    {
        public int Id { get; set; }
        public string PingMing { get; set; }
        public string HuoHao { get; set; }
        public string Guige { get; set; }
        public string SeHao { get; set; }
        public string Yanse { get; set; }
        public string DanJia { get; set; }
        public string GongHuoFangA { get; set; }
        public string GongHuoFangB { get; set; }
        public string BeiZhu { get; set; }
    }
}
