//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class KuanShiBiao
    {
        public int Id { get; set; }
        public string STYLE { get; set; }
        public string DESC { get; set; }
        public string FABRIC { get; set; }
        public string JACKET { get; set; }
        public string PANT { get; set; }
        public string ShuoMing { get; set; }
        public string mark1 { get; set; }
        public string mark2 { get; set; }
    }
}
