//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class KuCun
    {
        public int Id { get; set; }
        public string PingMing { get; set; }
        public string HuoHao { get; set; }
        public string SeHao { get; set; }
        public string ShuLiang { get; set; }
        public string GongHuoFang { get; set; }
        public string CunFangDI { get; set; }
    }
}
