//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class MianFuLiaoDingGouDan
    {
        public int Id { get; set; }
        public string PingMing { get; set; }
        public string GongFang { get; set; }
        public string XuFang { get; set; }
        public string HeTongHao { get; set; }
        public string QianYueDiDan { get; set; }
        public string QianYueShiJian { get; set; }
        public string HuoHao { get; set; }
        public string SeHao { get; set; }
        public string YanSe { get; set; }
        public string GuiGe { get; set; }
        public string DanWei { get; set; }
        public string DanJia { get; set; }
        public string ShuLiang { get; set; }
        public string ZongJinE { get; set; }
        public string CaiDanHao { get; set; }
    }
}
