//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsBuiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeiSe
    {
        public int Id { get; set; }
        public string Fabrics { get; set; }
        public string PingMing { get; set; }
        public string HuoHao { get; set; }
        public string GuiGe { get; set; }
        public string C61601C1 { get; set; }
        public string C61602C1 { get; set; }
        public string C61603C1 { get; set; }
        public string C61605C1 { get; set; }
        public string C61606C1 { get; set; }
        public string C61607C1 { get; set; }
        public string C61609C1 { get; set; }
        public string C61611C1 { get; set; }
        public string C61618C1 { get; set; }
        public string C61624C1 { get; set; }
        public string C61627C1 { get; set; }
        public string C61631C1 { get; set; }
        public string C61632C1 { get; set; }
        public string C61633C1 { get; set; }
        public string C61634C1 { get; set; }
        public string MianLiaoYanSe { get; set; }
        public string Date { get; set; }
    }
}
